export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const USER_FORM_SUBMIT = 'USER_FORM_SUBMIT';

export const DELETE_USER  = 'DELETE_USER ';