export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const USER_FORM_SUBMIT = "USER_FORM_SUBMIT";
export const DELETE_USER = "DELETE_USER ";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const SEND_PASSWORD_RESET_EMAIL = "SEND_PASSWORD_RESET_EMAIL";
export const RESET_PASSWORD = "RESET_PASSWORD ";
